### ISSUE TITLE
어플리케이션의 logs는 host의 /logs 디렉토리에 적재

### ISSUE THREAD

**Issue by SHsteak** [SHsteak/kakaopay-2020#3]

**Comment by SHsteak** [comment]
어플리케이션 컨테이너의 /logs에 운영 시 호스트의 /logs 디렉토리를 mount하여 적재할 예정이다.

/host_logs:/app_logs 와 같은 구조

**Comment by SHsteak** [comment]
# application.yml 수정

1분 단위로 log 파일을 rolling 한다

```yaml
logging:
  file:
    max-history: 30
    max-size: 10MB
    path: /logs
    name: /logs/app.log
  level:
    root: info
    org:
      springframework:
        #  context:
        #  annotation: TRACE
        web: DEBUG
    sql: debug
  pattern:
    rolling-file-name: /logs/app-%d{yyyy-MM-dd-HH-mm}.%i.log
    level:
```
