### ISSUE TITLE
DB도 kubernetes에서 실행하며 재 실행 시에도 변경된 데이터는 유실되지 않도록 설정한다

### ISSUE THREAD

**Issue by SHsteak** [SHsteak/kakaopay-2020#4]
## 순서

1. nfs 설정
2. k8s pv yaml 작성 및 적용
3. k8s secert 작성
4. k8s mysql deployment 작성
5. k8s secret에 리소스 추가
6. 적용

## 내용

- nfs 열기

    ```bash
    yum install -y nfs-utils

    mkdir -p /Data/mysql

    # *을 192.168.*.* 등 제한하는 것이 더욱 좋아보임
    cat > /etc/exports <<EOF
    /Data/mysql 192.168.*.*(rw,sync,no_root_squash)
    EOF

    systemctl enable --now nfs-server && systemctl enable --now rpcbind
    ```

- pv yaml 작성

    ```yaml
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: mysql-pv
      labels:
        app: mysql
    spec:
      capacity:
        storage: 3Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      storageClassName: standard
      mountOptions:
        - hard
        - nfsvers=4.1
      nfs:
        path: /Data/mysql
        server: 192.168.220.130
    ```

- secret yaml 작성

    ```yaml
    cat <<EOF >./kustomization.yaml
    secretGenerator:
    - name: mysql-pass
      literals:
      - password=petclinic
    EOF
    ```

- deployment yaml 작성

    ```yaml
    apiVersion: v1
    kind: Service
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      ports:
        - port: 3306
      selector:
        app: mysql
        tier: mysql
      externalIPs: ['192.168.220.130']
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mysql-pv-claim
      labels:
        app: mysql
    spec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
    ---
    apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
    kind: Deployment
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      selector:
        matchLabels:
          app: mysql
          tier: mysql
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: mysql
            tier: mysql
        spec:
          containers:
          - image: mysql:5.7
            name: mysql
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQL_DATABASE
              value: "petclinic"
            ports:
            - containerPort: 3306
              name: mysql
            volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          volumes:
          - name: mysql-persistent-storage
            persistentVolumeClaim:
              claimName: mysql-pv-claim
    ```

- 시크릿에 리소스 추가

    ```bash
    cat <<EOF >>./kustomization.yaml
    resources:
      - mysql-deployment.yaml
    EOF
    ```

- 실행

    ```yaml
    kubectl apply -k ./
    ```

**Comment by SHsteak** [comment]
## 내용

- nfs 열기

    ```bash
    yum install -y nfs-utils

    mkdir -p /Data/mysql

    # *을 192.168.*.* 등 제한하는 것이 더욱 좋아보임
    cat > /etc/exports <<EOF
    /Data/mysql 192.168.*.*(rw,sync,no_root_squash)
    EOF

    systemctl enable --now nfs-server && systemctl enable --now rpcbind
    ```

- pv yaml 작성

    ```yaml
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: mysql-pv
      labels:
        app: mysql
    spec:
      capacity:
        storage: 3Gi
      volumeMode: Filesystem
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      storageClassName: standard
      mountOptions:
        - hard
        - nfsvers=4.1
      nfs:
        path: /Data/mysql
        server: 192.168.220.130
    ```

- pvc yaml 작성

    ```yaml
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mysql-pv-claim
      labels:
        app: mysql
    spec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
    ```

- secret yaml 작성

    ```yaml
    cat <<EOF >./kustomization.yaml
    secretGenerator:
    - name: mysql-pass
      literals:
      - password=petclinic
    EOF
    ```

- deployment yaml 작성

    ```yaml
    apiVersion: v1
    kind: Service
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      ports:
        - name: mysql
          port: 3306
      selector:
        app: mysql
        tier: mysql
    ---
    apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
    kind: Deployment
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      selector:
        matchLabels:
          app: mysql
          tier: mysql
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: mysql
            tier: mysql
        spec:
          containers:
          - image: mysql:5.7
            name: mysql
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQL_DATABASE
              value: "petclinic"
            ports:
            - containerPort: 3306
              name: mysql
            volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          volumes:
          - name: mysql-persistent-storage
            persistentVolumeClaim:
              claimName: mysql-pv-claim
    ```

- 시크릿에 리소스 추가

    ```bash
    cat <<EOF >>./kustomization.yaml
    resources:
      - mysql-deployment.yaml
    EOF
    ```

- 실행

    ```yaml
    kubectl apply -k ./
    ```
