### ISSUE TITLE
어플리케이션은 Health Check.

### ISSUE THREAD

**Issue by SHsteak** [SHsteak/kakaopay-2020#7]
정상 동작 여부를 반환하는 api를 구현하며, 10초에 한번 체크하도록 한다. 3번 연속 체크에 실패하면 어플리케이션은 restart 된다.

**Comment by SHsteak** [comment]
### springboot actuator 사용

- application.properties

    ```yaml
    # 필요한 health api만 노출
    management.endpoints.web.base-path=/manage
    management.endpoints.web.exposure.include=health
    ```

### k8s Readiness 사용

- deployment.yaml

    ```yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: was-deployment
      labels:
        app: was
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: was
      template:
        metadata:
          labels:
            app: was
        spec:
          containers:
          - name: was
            image: choshsh/spring-petclinic-data-jdbc:latest
            ports:
            - name: http
              containerPort: 8080
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /manage/health/readiness
                port: 8080
              initialDelaySeconds: 30
              periodSeconds: 10
    ```

**Comment by SHsteak** [comment]
### image pull 시간과 어플리케이션이 완전히 실행되는 시간 때문인지 pod 생성 시 error와 함께 restart되는 현상이 있다.

아래 2가지를 사용하여 해결했다.

1. livenessProbe
2. startupProbe

먼저 Dockerfile에 /tmp/healthy를 추가했다.

`RUN touch /tmp/healthy`

- livenessProbe

    시작 시 30초를 기다린 후 10초 간격으로 6회까지 check

    ```yaml
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 30
      failureThreshold: 6
      periodSeconds: 10
    ```

- startupProbe

    ```yaml
    startupProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 30
      failureThreshold: 10
      periodSeconds: 10
    ```
