### ISSUE TITLE
nginx-ingress-controller를 통해 어플리케이션에 접속

### ISSUE THREAD

**Issue by SHsteak** [SHsteak/kakaopay-2020#8]
k8s의 was service와 외부 요청을 연결해주는 ingress를 설정해야 한다.

**Comment by SHsteak** [comment]
# ingress

nginx-ingress-controller를 사용하여 어플리케이션에 접속이 가능하도록 설정한다.

# 순서

1. nginx-ingress-controller 생성
2. nginx-ingress 및 서비스 생성

# 내용

## nginx-ingress-controller.yaml 생성

아래 yaml 파일을 다운받아 namespace와 apiVersion을 수정했다.
([https://raw.githubusercontent.com/kubernetes/ingress-nginx/2de5a893aa15f14102d714e918b0045b960ad1a5/deploy/static/mandatory.yaml](https://raw.githubusercontent.com/kubernetes/ingress-nginx/2de5a893aa15f14102d714e918b0045b960ad1a5/deploy/static/mandatory.yaml))

1. namespace를 default로 변경

    `:%s@namespace: ingress-nginx@namespace: default`

2. apiVersion beta 버전을 v1으로 수정

    `:%s@rbac.authorization.k8s.io/v1beta1@rbac.authorization.k8s.io/v1`

## nginx-ingress 및 서비스 생성

- nginx-ingress.yaml

    `host: www.choshsh.com` 는 `/etc/hosts`와 일치하도록 변경해야 한다.

    ```yaml
    kind: Service
    apiVersion: v1
    metadata:
      name: ingress-nginx
      namespace: default
      labels:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/part-of: ingress-nginx
    spec:
      externalTrafficPolicy: Local
      type: LoadBalancer
      selector:
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/part-of: ingress-nginx
      ports:
        - name: http
          port: 80
          targetPort: http
        - name: https
          port: 443
          targetPort: https
    ---
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: minimal-ingress
      annotations:
        ingress.kubernetes.io/rewrite-target: /
    spec:
      rules:
      - host: www.choshsh.com
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "was-service"
                port:
                  number: 8080
    ```
