### ISSUE TITLE
어플리케이션의 log는 host의 /logs 디렉토리에 적재되도록 한다

### ISSUE THREAD

**Issue by SHsteak** [SHsteak/kakaopay-2020#9]
간단하게 springboot의 logging 기능을 사용하려 했지만 매우 좋지 않은 선택인 것 같다..

어플리케이션이 각 node를 옮겨다니며 실행되기 때문에 중구난방으로 쌓인다..

ElasticSearch와 fluentd을 사용하는 것이 목표다.

**Comment by SHsteak** [comment]
Elasticsearch와 Fluentd를 사용하여 로깅해야 할 것 같은데 nfs pvc를 마운트하는데 실패했고 제출 시간이 지났다..

**Comment by SHsteak** [comment]
## elasticsearch.yaml

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elastic/elasticsearch:6.8.6
        env:
        - name: discovery.type
          value: "single-node"
        ports:
        - containerPort: 9200
        - containerPort: 9300
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-svc
  namespace: default
spec:
  ports:
  - name: elasticsearch-rest
    nodePort: 30482
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: elasticsearch-nodecom
    nodePort: 30930
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: elasticsearch
  type: NodePort
```

**Comment by SHsteak** [comment]
## fluentd.yaml

/var/log의 모든 로그를 `[http://elasticsearch-svc.default.svc.cluster.local:9200](http://elasticsearch-svc.default.svc.cluster.local:9200)` 에 적재한다.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: fluentd
  name: fluentd
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
      - "pods"
    verbs:
      - "list"
      - "get"
      - "watch"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentd
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: kube-system

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-elasticsearch-1.1
        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch-svc.default.svc.cluster.local"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENTD_SYSTEMD_CONF
            value: "disable"
          - name: FLUENT_UID
            value: "0"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
```

**Comment by SHsteak** [comment]
# elasticsearch가 사용할 퍼시스턴트볼륨

퍼시스턴트볼륨을 /usr/share/elasticsearch/data에 bind mount하여 로그 적재

### elasticsearch-pv.yaml

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv
  labels:
    app: elasticsearch
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /logs
    server: 192.168.220.130
```

### elasticsearch-pvc.yaml

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  labels:
    app: elasticsearch
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
```

**Comment by SHsteak** [comment]
### kibana.yaml

elasticsearch의 로그를 시각화하기 위한 kiabana manifest

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: kibana:7.9.3
        imagePullPolicy: IfNotPresent
        env:
        - name: ELASTICSERCH_UTL
          value: "http://elasticsearch-svc:9200"
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-svc:9200"
        - name: TZ
          value: "Asia/Seoul"
        ports:
        - containerPort: 5601
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
  name: kibana-svc
  namespace: default
spec:
  ports:
  - name: kibana-http
    port: 5601
  selector:
    app: kibana
  type: LoadBalancer
  externalIPs:
  - 192.168.220.130
```
